# Generated by Django 3.0.6 on 2021-02-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='create_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
