# Generated by Django 3.0.6 on 2021-02-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210212_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='create_on',
            new_name='created_on',
        ),
        migrations.AlterField(
            model_name='post',
            name='blog_image',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
    ]
