# Generated by Django 3.0.6 on 2021-02-15 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210214_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Contact'},
        ),
        migrations.RemoveField(
            model_name='reply',
            name='active',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='subject',
        ),
    ]
