# Generated by Django 3.0.6 on 2020-06-19 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name': 'Posts'},
        ),
        migrations.AlterModelTable(
            name='posts',
            table='blog',
        ),
    ]
