# Generated by Django 3.0.6 on 2020-06-19 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200619_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={},
        ),
        migrations.AlterModelTable(
            name='posts',
            table=None,
        ),
    ]
