# Generated by Django 3.0.6 on 2020-06-25 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pref', to='blog.Posts')),
            ],
            options={
                'verbose_name_plural': 'Prefereces',
            },
        ),
        migrations.DeleteModel(
            name='About',
        ),
    ]
